// Import styles conditionally based on the environment using dynamic imports
if (import.meta.env.PROD) {
  // In production, import the minified CSS created by the 'minify' scrip
  import('./assets/style.css');
} else {
  // In development, import the unminified CSS generated by the 'watch' script
  import('./assets/output.css');
}

import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'

const app = createApp(App)

app.use(createPinia())
app.use(router)

app.mount('#app')
